version: '3'
services:
  acf:
    image: ortussolutions/commandbox:latest
    ports: 
      - "8080:8080"
    container_name: text-to-speech
    env_file:
      - ./config/.env
    volumes:
      - ./www:/app